make test: modify query_tests.py to avoid an error if datatest.pkl does not exist
If make test s=... is invoked in a clean build:

$ make test s="eps_tutorials-ex2_1"
/usr/local/bin/gmake  --no-print-directory -f /Users/jroman/soft/slepc/gmakefile.test PETSC_ARCH=arch-darwin-c-debug PETSC_DIR=/Users/jroman/soft/petsc SLEPC_DIR=/Users/jroman/soft/slepc test
Traceback (most recent call last):
  File "/Users/jroman/soft/petsc/config/query_tests.py", line 378, in <module>
    main()
  File "/Users/jroman/soft/petsc/config/query_tests.py", line 371, in main
    do_query(opts.use_source, startdir, petsc_full_src, petsc_full_test,
  File "/Users/jroman/soft/petsc/config/query_tests.py", line 249, in do_query
    dataDict=get_gmakegentest_data(testdir, petsc_dir, petsc_arch)
  File "/Users/jroman/soft/petsc/config/query_tests.py", line 205, in get_gmakegentest_data
    fd = open(pkl_file, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './arch-darwin-c-debug/tests/datatest.pkl'

In that case, gmakegentest.py must be run on the SLEPc sources, so
query_tests.py must be modified (cannot use PETSc's one directly).